language: java
jdk:
  - oraclejdk8

# Notify development list when needed
notifications:
 recipients:
   - exkazuu@gmail.com
   - nnujabok@gmail.com
 email:
   on_success: change
   on_failure: always
